apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS BD_Sistema_BiBlioteca;
    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
    FLUSH PRIVILEGES;

    ALTER USER 'admin'@'%' IDENTIFIED WITH mysql_native_password BY 'admin';

    USE BD_Sistema_BiBlioteca;

    -- Crear tabla libros
    CREATE TABLE IF NOT EXISTS libros (
        cveLibro INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        tituloLibro VARCHAR(255) NOT NULL,
        autor VARCHAR(255) NOT NULL,
        fechaPublicacion DATE,
        genero VARCHAR(100),
        estatusPrestamo BOOLEAN,
        estatus BOOLEAN,
        imagen VARCHAR(2000)
    );

    -- Crear tabla usuarios
    CREATE TABLE IF NOT EXISTS usuarios (
      cveUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL,
      apellido_pa VARCHAR(255) NOT NULL, 
      apellido_ma VARCHAR(255) NOT NULL,
      correo VARCHAR(255) NOT NULL UNIQUE,
      contrasena VARCHAR(255) NOT NULL,
      direccion VARCHAR(255) NOT NULL,
      telefono VARCHAR(15) NOT NULL,
      rol TINYINT(1),
      estatus TINYINT(1)
    );

    -- Crear tabla historial_prestamo
    CREATE TABLE IF NOT EXISTS historialPrestamos (
        cveHistorial INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        cveUsuario INT NOT NULL,
        cveLibro INT NOT NULL,
        fechaPrestamo DATE,
        fechaDevolucion DATE,
        FOREIGN KEY (cveUsuario) REFERENCES usuario(cveUsuario),
        FOREIGN KEY (cveLibro) REFERENCES libro(cveLibro)
    );

    -- Crear tabla prestamo_digital
    CREATE TABLE IF NOT EXISTS prestamoDigital (
        cveDigital INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        cveUsuario INT NOT NULL,
        cveLibro INT NOT NULL,
        fechaDevolucion DATE,
        muestra BOOLEAN,
        FOREIGN KEY (cveUsuario) REFERENCES usuario(cveUsuario),
        FOREIGN KEY (cveLibro) REFERENCES libro(cveLibro)
    );