apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # "root" en base64
  MYSQL_DATABASE: QkRfU2lzdGVtYV9CaUJsaW90ZWNh  # "BD_Sistema_BiBlioteca" en base64